# Functional Class and Curvature Analysis
This notebook illustrates the complete analysis example using Here Map Content (HMC) attributes.

### Dependencies
* Catalogs: [rib-2](https://platform.here.com/data/hrn:here:data::olp-here:rib-2)
* Layers: [Topology Geometry](https://platform.here.com/data/hrn:here:data::olp-here:rib-2/topology-geometry), [Road Attributes](https://platform.here.com/data/hrn:here:data::olp-here:rib-2/road-attributes), [ADAS Attributes](https://platform.here.com/data/hrn:here:data::olp-here:rib-2/adas-attributes)

### Workflow
* Start with a bounding box that contains portions of two tiles
* Extract geometry for the two tiles
* Keep only the segments that are (at least partially) in original bounding box
* Extract Functional Class (FC) attributes for those segments
* Select segments with FC = 3, 4, and 5
* Extract curvature for the survived segments
* Analyze average curvature
* Drop segments below the average curvature

## Specify your HERE API key to use HERE Maps

In [1]:
import os
os.environ["LS_API_KEY"] = "YOUR HERE API KEY"

## Get partition ID's from a given bounding box

In [2]:
from here.geotiles.heretile import in_bounding_box
from shapely.geometry import Point

zoom_level = 12
west = 13.41
east = 13.49
south = 52.50
north = 52.54
center = Point(west, south)
tileIds = list(in_bounding_box(west=west, south=south, east=east, north=north, level=zoom_level))

# partition ID's: string representation of tile IDs - this will be used for extracting attributes later
partition_ids = [str(tile) for tile in tileIds]
print("partition ids:", partition_ids)

partition ids: ['23618402', '23618403']

## Visualize the bounding box and tile boundaries
- bounding box: Red
- tile boundaries: Gray

In [3]:
from here.inspector import inspect
from here.inspector.styles import Color
from shapely.geometry import Polygon

# construct a bounding box geojson
bb_polygon = Polygon([(west, south), (west, north), (east, north), (east, south), (west, south)])

# create inspect object with tile boundaries and the bounding box
inspect(layers={"bounding_box": [bb_polygon]},
        tiles=tileIds,
        center=center,
        zoom=11,
        layers_style={"bounding_box": Color.RED},
        tiles_style=Color.GRAY)

Map(center=[52.5, 13.41], controls=(LayersControl(options=['collapsed', 'position']), ZoomControl(options=['po…

## Extract topology geometry and clip by bounding box

In [4]:
from here.platform import Platform
from here.content.hmc2.hmc import HMC
from here.geopandas_adapter import GeoPandasAdapter
import pandas as pd
import geopandas as gpd

# create HMC object
hmc = HMC(Platform(), adapter=GeoPandasAdapter())

In [5]:
# get segments dataframe from given tiles
segment_df = hmc.topology_geometry.get(tileIds, "segment")
segment_df

                                       start_node_ref.partition  \
partition_id segment_id
23618402     here:cm:segment:100005273                 23618402
             here:cm:segment:100005274                 23618402
             here:cm:segment:100005285                 23618402
             here:cm:segment:100005286                 23618402
             here:cm:segment:100005287                 23618402
...                                                         ...
23618403     here:cm:segment:99973024                  23618403
             here:cm:segment:99973086                  23618403
             here:cm:segment:99983233                  23618403
             here:cm:segment:99990525                  23618403
             here:cm:segment:99994957                  23618403

                                       start_node_ref.identifier  \
partition_id segment_id
23618402     here:cm:segment:100005273    here:cm:node:850753878
             here:cm:segment:100005274    here:cm:node:850753876
             here:cm:segment:100005285    here:cm:node:850806348
             here:cm:segment:100005286     here:cm:node:61051173
             here:cm:segment:100005287    here:cm:node:850806349
...                                                          ...
23618403     here:cm:segment:99973024      here:cm:node:61081169
             here:cm:segment:99973086      here:cm:node:61042975
             here:cm:segment:99983233      here:cm:node:61080290
             here:cm:segment:99990525     here:cm:node:952743094
             here:cm:segment:99994957      here:cm:node:61061133

                                       end_node_ref.partition  \
partition_id segment_id
23618402     here:cm:segment:100005273               23618402
             here:cm:segment:100005274               23618402
             here:cm:segment:100005285               23618402
             here:cm:segment:100005286               23618402
             here:cm:segment:100005287               23618402
...                                                       ...
23618403     here:cm:segment:99973024                23618403
             here:cm:segment:99973086                23618403
             here:cm:segment:99983233                23618403
             here:cm:segment:99990525                23618403
             here:cm:segment:99994957                23618403

                                       end_node_ref.identifier  \
partition_id segment_id
23618402     here:cm:segment:100005273   here:cm:node:61059000
             here:cm:segment:100005274  here:cm:node:850753878
             here:cm:segment:100005285  here:cm:node:850806350
             here:cm:segment:100005286  here:cm:node:850806349
             here:cm:segment:100005287   here:cm:node:61051152
...                                                        ...
23618403     here:cm:segment:99973024    here:cm:node:61081168
             here:cm:segment:99973086    here:cm:node:61042976
             here:cm:segment:99983233    here:cm:node:61080287
             here:cm:segment:99990525   here:cm:node:952743093
             here:cm:segment:99994957    here:cm:node:61061134

                                                                                 geometry  \
partition_id segment_id
23618402     here:cm:segment:100005273  LINESTRING (13.44399 52.51531, 13.44405 52.515...
             here:cm:segment:100005274  LINESTRING (13.44347 52.51514, 13.44399 52.51531)
             here:cm:segment:100005285  LINESTRING (13.40016 52.49682, 13.39965 52.496...
             here:cm:segment:100005286  LINESTRING (13.40222 52.49641, 13.40076 52.49645)
             here:cm:segment:100005287  LINESTRING (13.40076 52.49645, 13.40018 52.49646)
...                                                                                   ...
23618403     here:cm:segment:99973024     LINESTRING (13.49611 52.5441, 13.4956 52.54424)
             here:cm:segment:99973086   LINESTRING (13.45018 52.47677, 13.45095 52.47737)
             here:cm:segment:99983233   LINESTRING (13.51952 52.49486, 13.51892 52.49584)
             here:cm:segment:99990525   LINESTRING (13.53283 52.48746, 13.53313 52.487...
             here:cm:segment:99994957   LINESTRING (13.46072 52.52957, 13.46079 52.529...

                                                                                  z_level  \
partition_id segment_id
23618402     here:cm:segment:100005273                                          [0, 0, 0]
             here:cm:segment:100005274                                             [0, 0]
             here:cm:segment:100005285                                 [0, 0, 0, 0, 0, 0]
             here:cm:segment:100005286                                             [0, 0]
             here:cm:segment:100005287                                             [0, 0]
...                                                                                   ...
23618403     here:cm:segment:99973024                                              [0, 0]
             here:cm:segment:99973086                                              [0, 0]
             here:cm:segment:99983233                                              [0, 0]
             here:cm:segment:99990525   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
             here:cm:segment:99994957                                           [0, 0, 0]

                                           length
partition_id segment_id
23618402     here:cm:segment:100005273   53.97453
             here:cm:segment:100005274   40.05030
             here:cm:segment:100005285  105.45831
             here:cm:segment:100005286   99.25682
             here:cm:segment:100005287   39.40682
...                                           ...
23618403     here:cm:segment:99973024    37.94505
             here:cm:segment:99973086    84.82251
             here:cm:segment:99983233   116.41634
             here:cm:segment:99990525   457.78907
             here:cm:segment:99994957    15.64068

[28026 rows x 7 columns]

### Clip segments by the bounding box
Since the geometry objects for the segment dataframe is LineString, the intersection method will do the clipping. See the documentation of shapely: https://shapely.readthedocs.io/en/stable/manual.html

In [6]:
clipped_segments = segment_df.intersection(bb_polygon)
segment_in_bb = segment_df[clipped_segments.apply(lambda x: x.length != 0)]
segment_in_bb

                                       start_node_ref.partition  \
partition_id segment_id
23618402     here:cm:segment:100005273                 23618402
             here:cm:segment:100005274                 23618402
             here:cm:segment:100036943                 23618402
             here:cm:segment:100036944                 23618402
             here:cm:segment:100095630                 23618402
...                                                         ...
23618403     here:cm:segment:99912978                  23618403
             here:cm:segment:99966244                  23618403
             here:cm:segment:99966357                  23618403
             here:cm:segment:99973008                  23618403
             here:cm:segment:99994957                  23618403

                                       start_node_ref.identifier  \
partition_id segment_id
23618402     here:cm:segment:100005273    here:cm:node:850753878
             here:cm:segment:100005274    here:cm:node:850753876
             here:cm:segment:100036943    here:cm:node:828712981
             here:cm:segment:100036944    here:cm:node:850831168
             here:cm:segment:100095630    here:cm:node:850843823
...                                                          ...
23618403     here:cm:segment:99912978     here:cm:node:858502534
             here:cm:segment:99966244      here:cm:node:61062298
             here:cm:segment:99966357      here:cm:node:61061654
             here:cm:segment:99973008      here:cm:node:61062264
             here:cm:segment:99994957      here:cm:node:61061133

                                       end_node_ref.partition  \
partition_id segment_id
23618402     here:cm:segment:100005273               23618402
             here:cm:segment:100005274               23618402
             here:cm:segment:100036943               23618402
             here:cm:segment:100036944               23618402
             here:cm:segment:100095630               23618402
...                                                       ...
23618403     here:cm:segment:99912978                23618403
             here:cm:segment:99966244                23618403
             here:cm:segment:99966357                23618403
             here:cm:segment:99973008                23618403
             here:cm:segment:99994957                23618403

                                       end_node_ref.identifier  \
partition_id segment_id
23618402     here:cm:segment:100005273   here:cm:node:61059000
             here:cm:segment:100005274  here:cm:node:850753878
             here:cm:segment:100036943  here:cm:node:850831168
             here:cm:segment:100036944  here:cm:node:810808453
             here:cm:segment:100095630   here:cm:node:61059309
...                                                        ...
23618403     here:cm:segment:99912978   here:cm:node:858502517
             here:cm:segment:99966244    here:cm:node:61062299
             here:cm:segment:99966357    here:cm:node:61061647
             here:cm:segment:99973008    here:cm:node:61062265
             here:cm:segment:99994957    here:cm:node:61061134

                                                                                 geometry  \
partition_id segment_id
23618402     here:cm:segment:100005273  LINESTRING (13.44399 52.51531, 13.44405 52.515...
             here:cm:segment:100005274  LINESTRING (13.44347 52.51514, 13.44399 52.51531)
             here:cm:segment:100036943  LINESTRING (13.42226 52.5279, 13.42192 52.5280...
             here:cm:segment:100036944  LINESTRING (13.42179 52.52816, 13.42143 52.528...
             here:cm:segment:100095630  LINESTRING (13.42487 52.5391, 13.42462 52.5391...
...                                                                                   ...
23618403     here:cm:segment:99912978   LINESTRING (13.46656 52.53448, 13.46684 52.53476)
             here:cm:segment:99966244      LINESTRING (13.47027 52.53993, 13.47023 52.54)
             here:cm:segment:99966357   LINESTRING (13.48814 52.50769, 13.48664 52.50791)
             here:cm:segment:99973008   LINESTRING (13.47133 52.53259, 13.47107 52.533...
             here:cm:segment:99994957   LINESTRING (13.46072 52.52957, 13.46079 52.529...

                                             z_level     length
partition_id segment_id
23618402     here:cm:segment:100005273     [0, 0, 0]   53.97453
             here:cm:segment:100005274        [0, 0]   40.05030
             here:cm:segment:100036943     [0, 0, 0]   43.06557
             here:cm:segment:100036944  [0, 0, 0, 0]   72.90009
             here:cm:segment:100095630     [0, 0, 0]   36.67210
...                                              ...        ...
23618403     here:cm:segment:99912978         [0, 0]   36.49382
             here:cm:segment:99966244         [0, 0]    8.24868
             here:cm:segment:99966357         [0, 0]  104.74824
             here:cm:segment:99973008      [0, 0, 0]  110.39244
             here:cm:segment:99994957      [0, 0, 0]   15.64068

[7050 rows x 7 columns]

In [7]:
# show the clipped segments and original tile boundaries
inspect(features=segment_in_bb["geometry"], tiles=tileIds, tiles_style=Color.GRAY)

Map(center=[52.5146485, 13.4472655], controls=(LayersControl(options=['collapsed', 'position']), ZoomControl(o…

## Get functional class attribute with segment reference

In [8]:
# get functional_class attributes
fc_df_seg = hmc.topology_attributes.get_referencing(tileIds, "functional_class", "segment")
fc_df_seg

                                                                                  segments  \
ref_partition ref_identifier
23618402      here:cm:segment:100005273  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005274  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005285  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005286  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005287  [{'ref': {'partition': '23618402', 'identifier...
...                                                                                    ...
23618403      here:cm:segment:99923638   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99923639   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99923641   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99956156   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99994957   [{'ref': {'partition': '23618403', 'identifier...

                                         forward  backward  \
ref_partition ref_identifier
23618402      here:cm:segment:100005273     True      True
              here:cm:segment:100005274     True      True
              here:cm:segment:100005285     True      True
              here:cm:segment:100005286     True      True
              here:cm:segment:100005287     True      True
...                                          ...       ...
23618403      here:cm:segment:99923638      True      True
              here:cm:segment:99923639      True      True
              here:cm:segment:99923641      True      True
              here:cm:segment:99956156      True      True
              here:cm:segment:99994957      True      True

                                        attribute.functional_class
ref_partition ref_identifier
23618402      here:cm:segment:100005273         FUNCTIONAL_CLASS_5
              here:cm:segment:100005274         FUNCTIONAL_CLASS_5
              here:cm:segment:100005285         FUNCTIONAL_CLASS_5
              here:cm:segment:100005286         FUNCTIONAL_CLASS_5
              here:cm:segment:100005287         FUNCTIONAL_CLASS_5
...                                                            ...
23618403      here:cm:segment:99923638          FUNCTIONAL_CLASS_4
              here:cm:segment:99923639          FUNCTIONAL_CLASS_4
              here:cm:segment:99923641          FUNCTIONAL_CLASS_4
              here:cm:segment:99956156          FUNCTIONAL_CLASS_4
              here:cm:segment:99994957          FUNCTIONAL_CLASS_4

[38389 rows x 4 columns]

## Select FC = 3, 4, or 5

In [9]:
# select FC = 3, 4, 5
fc345_df = fc_df_seg[
    (fc_df_seg["attribute.functional_class"] == "FUNCTIONAL_CLASS_3") |
    (fc_df_seg["attribute.functional_class"] == "FUNCTIONAL_CLASS_4") |
    (fc_df_seg["attribute.functional_class"] == "FUNCTIONAL_CLASS_5")
]
fc345_df

                                                                                  segments  \
ref_partition ref_identifier
23618402      here:cm:segment:100005273  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005274  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005285  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005286  [{'ref': {'partition': '23618402', 'identifier...
              here:cm:segment:100005287  [{'ref': {'partition': '23618402', 'identifier...
...                                                                                    ...
23618403      here:cm:segment:99923638   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99923639   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99923641   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99956156   [{'ref': {'partition': '23618403', 'identifier...
              here:cm:segment:99994957   [{'ref': {'partition': '23618403', 'identifier...

                                         forward  backward  \
ref_partition ref_identifier
23618402      here:cm:segment:100005273     True      True
              here:cm:segment:100005274     True      True
              here:cm:segment:100005285     True      True
              here:cm:segment:100005286     True      True
              here:cm:segment:100005287     True      True
...                                          ...       ...
23618403      here:cm:segment:99923638      True      True
              here:cm:segment:99923639      True      True
              here:cm:segment:99923641      True      True
              here:cm:segment:99956156      True      True
              here:cm:segment:99994957      True      True

                                        attribute.functional_class
ref_partition ref_identifier
23618402      here:cm:segment:100005273         FUNCTIONAL_CLASS_5
              here:cm:segment:100005274         FUNCTIONAL_CLASS_5
              here:cm:segment:100005285         FUNCTIONAL_CLASS_5
              here:cm:segment:100005286         FUNCTIONAL_CLASS_5
              here:cm:segment:100005287         FUNCTIONAL_CLASS_5
...                                                            ...
23618403      here:cm:segment:99923638          FUNCTIONAL_CLASS_4
              here:cm:segment:99923639          FUNCTIONAL_CLASS_4
              here:cm:segment:99923641          FUNCTIONAL_CLASS_4
              here:cm:segment:99956156          FUNCTIONAL_CLASS_4
              here:cm:segment:99994957          FUNCTIONAL_CLASS_4

[36602 rows x 4 columns]

In [10]:
# change indexes into actual columns
fc345_df = fc345_df.reset_index()
# rename columns for easier merging later on
fc345_df.rename(columns={'ref_partition': 'partition_id'}, inplace=True)
fc345_df.rename(columns={'ref_identifier': 'segment_id'}, inplace=True)
fc345_df

,partition_id,segment_id,segments,forward,backward,attribute.functional_class
0,23618402,here:cm:segment:100005273,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
1,23618402,here:cm:segment:100005274,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
2,23618402,here:cm:segment:100005285,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
3,23618402,here:cm:segment:100005286,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
4,23618402,here:cm:segment:100005287,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
...,...,...,...,...,...,...
36597,23618403,here:cm:segment:99923638,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4
36598,23618403,here:cm:segment:99923639,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4
36599,23618403,here:cm:segment:99923641,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4
36600,23618403,here:cm:segment:99956156,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4
36601,23618403,here:cm:segment:99994957,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4

In [11]:
# join two dataframe by partitionId, segmentId
segment_fc345_df = segment_in_bb.merge(fc345_df,
                                       how="inner",
                                       on=["partition_id", "segment_id"])
segment_fc345_df

,partition_id,segment_id,start_node_ref.partition,start_node_ref.identifier,end_node_ref.partition,end_node_ref.identifier,geometry,z_level,length,segments,forward,backward,attribute.functional_class
0,23618402,here:cm:segment:100005273,23618402,here:cm:node:850753878,23618402,here:cm:node:61059000,"LINESTRING (13.44399 52.51531, 13.44405 52.515...","[0, 0, 0]",53.97453,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
1,23618402,here:cm:segment:100005274,23618402,here:cm:node:850753876,23618402,here:cm:node:850753878,"LINESTRING (13.44347 52.51514, 13.44399 52.51531)","[0, 0]",40.05030,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
2,23618402,here:cm:segment:100036943,23618402,here:cm:node:828712981,23618402,here:cm:node:850831168,"LINESTRING (13.42226 52.5279, 13.42192 52.5280...","[0, 0, 0]",43.06557,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
3,23618402,here:cm:segment:100036944,23618402,here:cm:node:850831168,23618402,here:cm:node:810808453,"LINESTRING (13.42179 52.52816, 13.42143 52.528...","[0, 0, 0, 0]",72.90009,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
4,23618402,here:cm:segment:100105178,23618402,here:cm:node:61057576,23618402,here:cm:node:850815518,"LINESTRING (13.41467 52.50976, 13.41386 52.51013)","[0, 0]",68.69943,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9293,23618403,here:cm:segment:99966244,23618403,here:cm:node:61062298,23618403,here:cm:node:61062299,"LINESTRING (13.47027 52.53993, 13.47023 52.54)","[0, 0]",8.24868,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_3
9294,23618403,here:cm:segment:99966357,23618403,here:cm:node:61061654,23618403,here:cm:node:61061647,"LINESTRING (13.48814 52.50769, 13.48664 52.50791)","[0, 0]",104.74824,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5
9295,23618403,here:cm:segment:99973008,23618403,here:cm:node:61062264,23618403,here:cm:node:61062265,"LINESTRING (13.47133 52.53259, 13.47107 52.533...","[0, 0, 0]",110.39244,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5
9296,23618403,here:cm:segment:99973008,23618403,here:cm:node:61062264,23618403,here:cm:node:61062265,"LINESTRING (13.47133 52.53259, 13.47107 52.533...","[0, 0, 0]",110.39244,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5
9297,23618403,here:cm:segment:99994957,23618403,here:cm:node:61061133,23618403,here:cm:node:61061134,"LINESTRING (13.46072 52.52957, 13.46079 52.529...","[0, 0, 0]",15.64068,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_4

## Show the segments with FC = 3, 4, or 5

In [12]:
inspect(segment_fc345_df["geometry"])

Map(center=[np.float64(52.519724999999994), np.float64(13.452165)], controls=(LayersControl(options=['collapse…

## Show different colors for each FC

In [13]:
fcs = {}
for fc, gdf in segment_fc345_df.groupby("attribute.functional_class"):
    fcs[fc] = gdf["geometry"]
inspect(layers=fcs)

Map(center=[np.float64(52.519724999999994), np.float64(13.452165)], controls=(LayersControl(options=['collapse…

## Extract curvatures

In [14]:
# get segment curvatures (curvatures at the nodes are not used in this notebook example)
segment_curvature_df = hmc.adas_attributes.get(partition_ids, "curvature")
segment_curvature_df

                                                segment_anchors  curvature
partition_id
23618402      [SegmentAnchor(partition_id='23618402', orient...    -650236
23618402      [SegmentAnchor(partition_id='23618402', orient...    -501807
23618402      [SegmentAnchor(partition_id='23618402', orient...    -487694
23618402      [SegmentAnchor(partition_id='23618402', orient...    -449294
23618402      [SegmentAnchor(partition_id='23618402', orient...    -449064
...                                                         ...        ...
23618403      [SegmentAnchor(partition_id='23618403', orient...     368847
23618403      [SegmentAnchor(partition_id='23618403', orient...     547620
23618403      [SegmentAnchor(partition_id='23618403', orient...     684539
23618403      [SegmentAnchor(partition_id='23618403', orient...     740088
23618403      [SegmentAnchor(partition_id='23618403', orient...     827914

[40542 rows x 2 columns]

## Select segments with high curvatures

In [15]:
# create a column called abs_curvature to calculate average curvature
segment_curvature_df["abs_curvature"] = segment_curvature_df.apply(lambda x: abs(x["curvature"]), axis=1)
average_curvature = segment_curvature_df["abs_curvature"].mean()

# select segments with curvature higher than average
highcurv_segments = segment_curvature_df[segment_curvature_df["abs_curvature"] > average_curvature]

# extract segment_id from segment anchors
highcurv_segments = highcurv_segments.copy()
highcurv_segments["segment_id"] = highcurv_segments.apply(
    lambda x: x["segment_anchors"][0].oriented_segment_ref[0][0].segment_id,
    axis=1
)

highcurv_segments

,segment_anchors,curvature,abs_curvature,segment_id
partition_id,,,,
23618402,"[SegmentAnchor(partition_id='23618402', orient...",-650236,650236,here:cm:segment:146671023
23618402,"[SegmentAnchor(partition_id='23618402', orient...",-501807,501807,here:cm:segment:116126247
23618402,"[SegmentAnchor(partition_id='23618402', orient...",-487694,487694,here:cm:segment:847729117
23618402,"[SegmentAnchor(partition_id='23618402', orient...",-449294,449294,here:cm:segment:90627216
23618402,"[SegmentAnchor(partition_id='23618402', orient...",-449064,449064,here:cm:segment:206150699
...,...,...,...,...
23618403,"[SegmentAnchor(partition_id='23618403', orient...",368847,368847,here:cm:segment:796959311
23618403,"[SegmentAnchor(partition_id='23618403', orient...",547620,547620,here:cm:segment:800999575
23618403,"[SegmentAnchor(partition_id='23618403', orient...",684539,684539,here:cm:segment:93469872
23618403,"[SegmentAnchor(partition_id='23618403', orient...",740088,740088,here:cm:segment:915081814
23618403,"[SegmentAnchor(partition_id='23618403', orient...",827914,827914,here:cm:segment:78486596

## Join two dataframes
Inner join between the dataframe with FC=3,4,5 and the dataframe with high curvatures

In [16]:
segment_fc345_highcurv_df = segment_fc345_df.merge(highcurv_segments,
                                                   how="inner",
                                                   on=["partition_id", "segment_id"])
segment_fc345_highcurv_df

,partition_id,segment_id,start_node_ref.partition,start_node_ref.identifier,end_node_ref.partition,end_node_ref.identifier,geometry,z_level,length,segments,forward,backward,attribute.functional_class,segment_anchors,curvature,abs_curvature
0,23618402,here:cm:segment:100036944,23618402,here:cm:node:850831168,23618402,here:cm:node:810808453,"LINESTRING (13.42179 52.52816, 13.42143 52.528...","[0, 0, 0, 0]",72.90009,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618402', orient...",-34734,34734
1,23618402,here:cm:segment:100036944,23618402,here:cm:node:850831168,23618402,here:cm:node:810808453,"LINESTRING (13.42179 52.52816, 13.42143 52.528...","[0, 0, 0, 0]",72.90009,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618402', orient...",-29622,29622
2,23618402,here:cm:segment:100115715,23618402,here:cm:node:850815516,23618402,here:cm:node:850815517,"LINESTRING (13.41399 52.50978, 13.41368 52.50988)","[0, 0]",23.80802,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618402', orient...",-73678,73678
3,23618402,here:cm:segment:100167158,23618402,here:cm:node:850806585,23618402,here:cm:node:61058364,"LINESTRING (13.43119 52.5225, 13.43128 52.5225...","[0, 0, 0, 0, 0, 0]",129.88355,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618402', orient...",-29698,29698
4,23618402,here:cm:segment:100167158,23618402,here:cm:node:850806585,23618402,here:cm:node:61058364,"LINESTRING (13.43119 52.5225, 13.43128 52.5225...","[0, 0, 0, 0, 0, 0]",129.88355,"[{'ref': {'partition': '23618402', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618402', orient...",31649,31649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4887,23618403,here:cm:segment:99880672,23618403,here:cm:node:858500470,23618403,here:cm:node:858500471,"LINESTRING (13.4664 52.53995, 13.46634 52.5400...","[0, 0, 0, 0]",29.05411,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618403', orient...",-30742,30742
4888,23618403,here:cm:segment:99902302,23618403,here:cm:node:61062114,23618403,here:cm:node:858502516,"LINESTRING (13.46303 52.53233, 13.46274 52.53242)","[0, 0]",22.08127,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618403', orient...",-41097,41097
4889,23618403,here:cm:segment:99902305,23618403,here:cm:node:858502518,23618403,here:cm:node:858502520,"LINESTRING (13.4657 52.53673, 13.4653 52.53685...","[0, 0, 0]",71.46301,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618403', orient...",-41967,41967
4890,23618403,here:cm:segment:99902309,23618403,here:cm:node:858502524,23618403,here:cm:node:858502518,"LINESTRING (13.46562 52.53624, 13.46579 52.536...","[0, 0, 0, 0]",58.00600,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618403', orient...",27910,27910
4891,23618403,here:cm:segment:99966357,23618403,here:cm:node:61061654,23618403,here:cm:node:61061647,"LINESTRING (13.48814 52.50769, 13.48664 52.50791)","[0, 0]",104.74824,"[{'ref': {'partition': '23618403', 'identifier...",True,True,FUNCTIONAL_CLASS_5,"[SegmentAnchor(partition_id='23618403', orient...",31004,31004

In [17]:
# drop abs_curvature which was used to calculate average curvature
merged_df = segment_fc345_highcurv_df.drop("abs_curvature", axis=1)
merged_df.columns

Index(['partition_id', 'segment_id', 'start_node_ref.partition',
       'start_node_ref.identifier', 'end_node_ref.partition',
       'end_node_ref.identifier', 'geometry', 'z_level', 'length', 'segments',
       'forward', 'backward', 'attribute.functional_class', 'segment_anchors',
       'curvature'],
      dtype='object')

## Show the survived segments

In [18]:
inspect(merged_df["geometry"])

Map(center=[np.float64(52.519815), np.float64(13.452465)], controls=(LayersControl(options=['collapsed', 'posi…

<!--
from urllib.parse import quote, unquote
svg = """<svg width="40" height="48" viewBox="0 0 40 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path class="triangle" d="M11,36.8l-5.5,5.5L0,36.8H11z" fill="#48DAD0"></path><path class="HERE" d="M19.1,24.2c-1.2-1.4-1.1-2.1-0.4-2.8c0.9-0.9,1.7-0.5,2.7,0.5L19.1,24.2z M30.9,9.2c0.9-0.9,1.7-0.5,2.7,0.5
    L31.3,12C30.1,10.7,30.2,9.9,30.9,9.2z M38,11.6c-1.1,1.6-2.9,4.2-4.9,2.2l5-5c-0.4-0.5-0.8-0.9-1-1.1c-2.7-2.7-5.7-2.7-8-0.4
	c-1.6,1.6-2,3.4-1.5,5.1l-1.6-1.8c-0.5,0.3-2.4,1.9-0.9,4.5l-1.8-1.5l-2.4,2.4l3.2,3.2c-2.5-1.9-5.1-1.8-7.2,0.4
	c-2.3,2.3-2.1,5-0.4,7.3l-0.3-0.3c-2.3-2.3-4.7-1.5-5.9-0.3c-0.9,0.9-1.5,2.2-1.3,3.1L4,24.6l-2.6,2.6l9.6,9.6h5.2l-3.5-3.5
	c-1.8-1.8-1.8-2.8-1-3.7c0.8-0.8,1.8-0.3,3.6,1.4l3.4,3.4l2.6-2.6l-3.2-3.2c2.3,1.8,5.1,1.9,7.7-0.6l0,0c1.5-1.4,2-2.8,2-2.8
	l-1.9-1.3c-1.1,1.6-2.9,4.2-4.9,2.3l5-5l3.1,3.1l2.7-2.7l-3.9-3.9c-1.8-1.8-0.7-3.5,0-4.1c0.4,0.7,0.9,1.5,1.5,2.1
	c2.5,2.5,5.7,3,8.6,0.2l0,0c1.5-1.4,2-2.8,2-2.8S38,11.6,38,11.6z" fill="#000000"></path></svg>
"""
print(f"""![HERE](data:image/svg+xml,{quote(svg)})
<span style="float:right; width:90%;"><sub><b>Copyright (c) 2020-2025 HERE Global B.V. and its affiliate(s). All rights reserved.</b>
This software, including documentation, is protected by copyright controlled by HERE. All rights are reserved. Copying, including reproducing, 
storing, adapting or translating, any or all of this material requires the prior written consent of HERE. This material also contains confidential 
information which may not be disclosed to others without the prior written consent of HERE.</sub></span>""")
-->
![HERE](data:image/svg+xml,%3Csvg%20width%3D%2240%22%20height%3D%2248%22%20viewBox%3D%220%200%2040%2048%22%20fill%3D%22none%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%3Cpath%20class%3D%22triangle%22%20d%3D%22M11%2C36.8l-5.5%2C5.5L0%2C36.8H11z%22%20fill%3D%22%2348DAD0%22%3E%3C/path%3E%3Cpath%20class%3D%22HERE%22%20d%3D%22M19.1%2C24.2c-1.2-1.4-1.1-2.1-0.4-2.8c0.9-0.9%2C1.7-0.5%2C2.7%2C0.5L19.1%2C24.2z%20M30.9%2C9.2c0.9-0.9%2C1.7-0.5%2C2.7%2C0.5%0A%20%20%20%20L31.3%2C12C30.1%2C10.7%2C30.2%2C9.9%2C30.9%2C9.2z%20M38%2C11.6c-1.1%2C1.6-2.9%2C4.2-4.9%2C2.2l5-5c-0.4-0.5-0.8-0.9-1-1.1c-2.7-2.7-5.7-2.7-8-0.4%0A%09c-1.6%2C1.6-2%2C3.4-1.5%2C5.1l-1.6-1.8c-0.5%2C0.3-2.4%2C1.9-0.9%2C4.5l-1.8-1.5l-2.4%2C2.4l3.2%2C3.2c-2.5-1.9-5.1-1.8-7.2%2C0.4%0A%09c-2.3%2C2.3-2.1%2C5-0.4%2C7.3l-0.3-0.3c-2.3-2.3-4.7-1.5-5.9-0.3c-0.9%2C0.9-1.5%2C2.2-1.3%2C3.1L4%2C24.6l-2.6%2C2.6l9.6%2C9.6h5.2l-3.5-3.5%0A%09c-1.8-1.8-1.8-2.8-1-3.7c0.8-0.8%2C1.8-0.3%2C3.6%2C1.4l3.4%2C3.4l2.6-2.6l-3.2-3.2c2.3%2C1.8%2C5.1%2C1.9%2C7.7-0.6l0%2C0c1.5-1.4%2C2-2.8%2C2-2.8%0A%09l-1.9-1.3c-1.1%2C1.6-2.9%2C4.2-4.9%2C2.3l5-5l3.1%2C3.1l2.7-2.7l-3.9-3.9c-1.8-1.8-0.7-3.5%2C0-4.1c0.4%2C0.7%2C0.9%2C1.5%2C1.5%2C2.1%0A%09c2.5%2C2.5%2C5.7%2C3%2C8.6%2C0.2l0%2C0c1.5-1.4%2C2-2.8%2C2-2.8S38%2C11.6%2C38%2C11.6z%22%20fill%3D%22%23000000%22%3E%3C/path%3E%3C/svg%3E%0A)
<span style="float:right; width:90%;"><sub><b>Copyright (c) 2020-2025 HERE Global B.V. and its affiliate(s). All rights reserved.</b>
This software, including documentation, is protected by copyright controlled by HERE. All rights are reserved. Copying, including reproducing, 
storing, adapting or translating, any or all of this material requires the prior written consent of HERE. This material also contains confidential 
information which may not be disclosed to others without the prior written consent of HERE.</sub></span>